### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by Hodo-** [Hodo-/dsn1674-assignment-6#2]
@thomasjbradley I have arranged all the images in a correct order, but I have yet to figure out how to move one of the images using a:hover. When I use the position under a:hover in css to do so, it just disappears when I hover over the image. What should I do?

**Comment by Hodo-** [comment]
Also, how do I make the brain only appear when a mouse hovers over it?

**Comment by thomasjbradley** [comment]
The key to the hovering is thinking about which thing is actually being hovered: Is it the face piece itself? Or is the whole robot?

---

_The brain:_

It's already there, just in behind the other face pieces. When hovered, it just moves upwards.
